version: '3'
services:
  metatrader:
    build: .
    ports:
      - "5900:5900"
      - "15555:15555"
      - "15556:15556"
      - "15557:15557"
      - "15558:15558"
    volumes:
      - ./Metatrader:/root/Metatrader
      

